services:

  pgm:
    container_name: PGm
    image: postgres:16
    restart: unless-stopped
    volumes:
      - pgv:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:5432

  adminer:
    container_name: ADm
    env_file:
      - .env
    image: adminer:latest
    restart: unless-stopped
    depends_on:
      - pgm
    environment:
      ADMINER_DEFAULT_SERVER: ${DB_HOST}
    ports:
      - 8081:8080

volumes:
  pgv:
    name: PGv

networks:
  default:
    name: prodnet